spring.application.name=distributed-database-project-server
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
spring.datasource.username=app_global_user
spring.datasource.password=set-manually
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
server.port=8081
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
project.jwt.secret-key=set-manually